baseURL = 'https://example.com'
languageCode = 'zh-cn'
title = '七哇夸'
copyright = '七哇夸'
theme = 'PaperMod'
pagination.pagerSize = 9
hasCJKLanguage = true
enableEmoji = true
timeZone = 'Asia/Shanghai'

[params]
    author = "我的名字"
    description = "一个基于 Hugo 的个人博客"
    subtitle = "Farroadeta"

[params.authorSignatures]
    qiwa = "月瘦梦肥，此为心乡"
    shangren = "一共是五亿零一百六十二万二千七百三十一颗星星"
    dilixuejia = "我们不记载花，因为花是转瞬即逝的"
    xiaowangzi = "有一天我看了四十四次日落"
    huli = "If you tame me,we'll need each other."
    meigui = "我是独一无二的玫瑰"
    she = "我有一切的谜语"
    jiugui = "喝酒是为了忘记"

[params.social]
    github = "https://github.com"
    twitter = "https://twitter.com"

[params.features]
    toc = true
    code_copy = true

[[menus.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

[[menus.main]]
    identifier = "archives"
    name = "归档"
    url = "/posts"
    weight = 2

[module]
    [module.hugoVersion]
        extended = true
        min = "0.116.0"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        style = "evergarden"
        tabWidth = 4
        codeFences = true
        guessSyntax = true

[outputs]
    home = ["HTML", "JSON"]

[permalinks]
    posts = "/posts/:year/:month/:day/:slug/"
    character = "/character/:slug/"
